#!/usr/bin/env bash
# common.sh — shared helpers for notes tasks

# The notes tool's own repo (for sourcing lib files, running python scripts)
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# The target repo is always CALLER_PWD (set by shiv shim)
TARGET_DIR="${CALLER_PWD:-.}"

require_git() {
  if ! git -C "$TARGET_DIR" rev-parse --git-dir &>/dev/null; then
    echo "Error: not a git repository: $TARGET_DIR" >&2
    exit 1
  fi
}

is_initialized() {
  [ -d "$TARGET_DIR/.git/git-crypt" ]
}

require_initialized() {
  if ! is_initialized; then
    echo "Error: git-crypt not initialized. Run: notes encrypt:setup" >&2
    exit 1
  fi
}

# Regenerate the COLLABORATORS manifest from .gpg key files.
# Includes identity, fingerprint, and full armored public key for each
# collaborator. This makes the repo self-contained — anyone can see who
# has access and import their public key without external tools.
#
# Fingerprints are derived from public keys (SHA-1 of the key packet),
# so the chain is verifiable: import the key block, compute the
# fingerprint, confirm it matches. Git history provides an audit trail
# of when each key was added or removed.
update_collaborators() {
  local keys_dir="$TARGET_DIR/.git-crypt/keys/default/0"
  local manifest="$keys_dir/COLLABORATORS"
  [ -d "$keys_dir" ] || return 0

  local has_keys=false
  for keyfile in "$keys_dir"/*.gpg; do
    [ -f "$keyfile" ] && has_keys=true && break
  done

  if ! $has_keys; then
    # No collaborators yet — write header only
    echo "# Who can decrypt this repo — auto-generated by notes encrypt:setup/add-user" > "$manifest"
    return 0
  fi

  {
    echo "# Who can decrypt this repo"
    echo "# Auto-generated by notes encrypt:setup/add-user"
    echo "#"
    echo "# Each entry includes the collaborator's full GPG public key."
    echo "# Fingerprints are derived from public keys — verify with:"
    echo "#   gpg --import <key-block> && gpg --fingerprint <email>"
    echo ""

    local first=true
    for keyfile in "$keys_dir"/*.gpg; do
      [ -f "$keyfile" ] || continue

      local fingerprint
      fingerprint=$(basename "$keyfile" .gpg)
      local uid
      uid=$(gpg --list-keys --with-colons "$fingerprint" 2>/dev/null \
        | awk -F: '/^uid/{print $10; exit}')

      if $first; then
        first=false
      else
        echo ""
      fi

      echo "## ${uid:-unknown}"
      echo "## Fingerprint: $fingerprint"
      gpg --armor --export "$fingerprint" 2>/dev/null
    done
  } > "$manifest"
}
